spring:
  application:
    name: aip-gatway
server:
  port: 8000


eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:1111/eureka/
zuul:
  routes:
    order:
      path: /order-service/**
      serviceId: order-service