server:
  port: 8001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/longfeizheng/springcloudDemo     # 配置git仓库的地址
          search-paths: config-git/config-repo                     # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: username                                              # git仓库的账号
          password: passoword